version: "3.9"
services:
  backend: 
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: albla20/backend:latest
    ports: 
    - 9000
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: albla20/frontend:latest
    ports:
    - 8080
    depends_on:
    - backend