name: main workflow
on: 
  push:
    branches:
    - main
  pull_request:
    branches: 
    - main
env: 
     docker_username: ${{ github.actor }} 
     docker_password: ${{ secrets.GITHUB_TOKEN }} 
     GIT_COMMIT: ${{ github.sha }}
jobs:
    Build: 
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21.12'
      - name: Build backend
        run: |
          cd backend 
          go build .
      - name: Build frontend
        run: |
          cd frontend 
          go build .
      - name: test frontend
        run: |
          cd frontend 
          go test ./...
      - name: Checkout
        uses: actions/checkout@v3
      - name: login to docker hub
        uses: docker/login-action@v3
        with:
          username: ${{env.docker_username}}
          password: ${{ env.docker_password }}
      - name: Build and push Docker images
        run: |
          docker build -t mathiasoverby/backend:latest ./backend
          docker push mathiasoverby/backend:latest
          docker build -t mathiasoverby/frontend:latest ./frontend
          docker push mathiasoverby/frontend:latest
      - name: pull docker images
        run: |
          docker pull mathiasoverby/backend:latest
          docker pull mathiasoverby/frontend:latest
