name: main workflow
on: 
  push:
    branches:
    - main
  pull_request:
    branches: 
    - main
jobs:
    Build: 
      runs-on: ubuntu-latest
      
      steps:
        - name: Build
          run: go build
        - name: test frontend
          run: go test
