name: main workflow
on: 
  push:
    branches:
    - main
  pull_request:
    branches: 
    - main
env: 
     docker_username: ${{ github.actor }} 
     docker_password: ${{ secrets.GITHUB_TOKEN }} 
     GIT_COMMIT: ${{ github.sha }}
jobs:
    Build: 
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21.12'
      - name: Build backend
        run: |
          cd backend 
          go build .
      - name: Build frontend
        run: |
          cd frontend 
          go build .
      - name: test frontend
        run: |
          cd frontend 
          go test ./...
      - name: Checkout
        uses: actions/checkout@v3


      - name: Build and push
        run: |
          IMAGE=backend/Dockerfile
          IMAGE=frontend/Dockerfile
          docker build -t mathiasoverby/frontend:latest .
          docker build -t mathiasoverby/backend:latest .

          docker push $IMAGE
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and push
        run: |
          IMAGE=mathiasoverby/backend:latest
          IMAGE=mathiasoverby/frontend:latest
          docker build -t $IMAGE .
          docker push $IMAGE
