name: main workflow
on: 
  push:
    branches:
    - main
  pull_request:
    branches: 
    - main
jobs:
    Build: 
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21.12'
      - name: Build backend
        run: |
          cd backend 
          go build .
      - name: Build frontend
        run: |
          cd frontend 
          go build .
      - name: test frontend
        run: |
          cd frontend 
          go test ./...
        
